#!/usr/bin/env bash
set -euo pipefail

# Decide whether one agent/base image needs to be rebuilt and append it to the shared build list.
#
# Interface:
#   --aicage-version <tag>        Required release tag used in the final image name.
#   --agent <name>               Required agent directory name.
#   --base-alias <alias>         Required base alias to compare against.
#   --agent-version <version>    Required agent version string from agents/<agent>/version.sh.
#   --build-list <path>          Required shared TSV file for rebuild selections.
#   --build-list-lock <path>     Required flock lock file protecting build-list writes.
#   --base-metadata-file <path>  Required TSV cache produced by matrix.sh.
#   --force-build                Optional bypass for registry checks; appends immediately.
#
# Output:
#   stdout/stderr are captured by matrix.sh into a per-worker log file.
#   Successful runs print status lines; failures return non-zero so matrix.sh can surface them.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"

source "${ROOT_DIR}/scripts/common.sh"
source "${ROOT_DIR}/scripts/refresh-images/lib.sh"

AICAGE_VERSION=""
AGENT=""
BASE_ALIAS=""
AGENT_VERSION=""
BUILD_LIST=""
BUILD_LIST_LOCK=""
BASE_METADATA_FILE=""
FORCE_BUILD=0

# Read one field from the base metadata TSV generated by matrix.sh.
read_base_metadata_field() {
  local metadata_file="$1"
  local base_alias="$2"
  local arch="$3"
  local field="$4"
  local field_index

  case "${field}" in
    digest)
      field_index=3
      ;;
    last_layer)
      field_index=4
      ;;
    *)
      echo "Unknown base metadata field: ${field}" >&2
      return 1
      ;;
  esac

  awk -F '\t' \
    -v base_alias="${base_alias}" \
    -v arch="${arch}" \
    -v field_index="${field_index}" \
    '$1 == base_alias && $2 == arch { print $field_index; found = 1; exit }
     END { if (!found) exit 1 }' \
    "${metadata_file}"
}

# Return codes:
#   0 => rebuild required
#   1 => image is up to date
#   2 => check failed
#
# The comparison validates that the final image exists for both arches and still contains the
# last layer from the current base image for each architecture.
needs_rebuild() {
  local base_image_tag="$1"
  local final_image_tag="$2"
  local base_metadata_file="$3"
  local base_repo="${AICAGE_IMAGE_REGISTRY}/${AICAGE_IMAGE_BASE_REPOSITORY}"
  local final_repo="${AICAGE_IMAGE_REGISTRY}/${AICAGE_IMAGE_REPOSITORY}"
  local base_image="${base_repo}:${base_image_tag}"
  local final_image="${final_repo}:${final_image_tag}"

  echo "[needs-rebuild]: base_image=${base_image}" >&2
  echo "[needs-rebuild]: final_image=${final_image}" >&2

  if ! skopeo_inspect --no-tags "docker://${final_image}" >/dev/null; then
    echo "${final_image} is missing"
    return 0
  fi

  for arch in amd64 arm64; do
    local base_digest
    if ! base_digest="$(read_base_metadata_field "${base_metadata_file}" "${base_image_tag}" "${arch}" digest)"; then
      echo "Missing cached ${arch} digest for ${base_image}" >&2
      return 2
    fi
    if [[ -z "${base_digest}" ]]; then
      echo "Missing cached ${arch} digest for ${base_image}" >&2
      return 2
    fi

    local final_digest
    if ! final_digest="$(get_manifest_digest "${final_image}" "${arch}")"; then
      echo "Failed to get ${arch} digest for ${final_image}" >&2
      return 2
    fi
    if [[ -z "${final_digest}" ]]; then
      echo "Missing ${arch} digest for ${final_image}"
      return 0
    fi

    local base_last_layer
    if ! base_last_layer="$(read_base_metadata_field "${base_metadata_file}" "${base_image_tag}" "${arch}" last_layer)"; then
      echo "Missing cached last layer for ${base_image} (${arch})" >&2
      return 2
    fi
    if [[ -z "${base_last_layer}" ]]; then
      echo "Missing cached last layer for ${base_image} (${arch})" >&2
      return 2
    fi

    local final_layers
    if ! final_layers="$(skopeo_inspect --no-tags "docker://${final_repo}@${final_digest}")"; then
      return 2
    fi
    if ! final_layers="$(run_cmd "jq layers ${final_repo}@${final_digest}" \
      jq -r '.Layers[]' <<<"${final_layers}")"; then
      return 2
    fi

    if ! printf '%s\n' "${final_layers}" | grep -Fxq "${base_last_layer}"; then
      echo "${final_repo}@${final_digest} missing base layer ${base_last_layer} (${arch})"
      return 0
    fi
  done

  return 1
}

# Append one rebuild decision to the shared build list. A lock is required because matrix.sh
# runs many of these workers concurrently.
append_build() {
  local agent="$1"
  local base_alias="$2"

  # Multiple check workers append to the same file concurrently.
  flock "${BUILD_LIST_LOCK}" \
    bash -c 'printf "%s\t%s\n" "$1" "$2" >> "$3"' \
    _ \
    "${agent}" \
    "${base_alias}" \
    "${BUILD_LIST}"
}

print_needs_rebuild_output() {
  [[ -n "${NEEDS_REBUILD_OUTPUT:-}" ]] || return 0
  printf '%s\n' "${NEEDS_REBUILD_OUTPUT}" | sed 's/^/  /'
}

# Run needs_rebuild while preserving its stdout/stderr for later logging.
needs_rebuild_status() {
  local agent="$1"
  local base_alias="$2"
  local agent_version="$3"
  local status

  set +e
  NEEDS_REBUILD_OUTPUT="$(
    needs_rebuild \
      "${base_alias}" \
      "${agent}-${agent_version}-${base_alias}-${AICAGE_VERSION}" \
      "${BASE_METADATA_FILE}" 2>&1
  )"
  status=$?
  set -e

  return "${status}"
}

main() {
  local status

  [[ -n "${AGENT}" ]] || _die "AGENT argument required"
  [[ -n "${BASE_ALIAS}" ]] || _die "BASE_ALIAS argument required"
  [[ -n "${AGENT_VERSION}" ]] || _die "AGENT_VERSION argument required"
  [[ -n "${BUILD_LIST}" ]] || _die "BUILD_LIST argument required"
  [[ -n "${BUILD_LIST_LOCK}" ]] || _die "BUILD_LIST_LOCK argument required"
  [[ -n "${BASE_METADATA_FILE}" ]] || _die "BASE_METADATA_FILE argument required"
  [[ -n "${AICAGE_VERSION}" ]] || _die "AICAGE_VERSION argument required"

  load_config_file

  if (( FORCE_BUILD )); then
    echo "Forcing build for ${AGENT} (${BASE_ALIAS})"
    append_build "${AGENT}" "${BASE_ALIAS}"
    return 0
  fi

  if needs_rebuild_status "${AGENT}" "${BASE_ALIAS}" "${AGENT_VERSION}"; then
    status=0
  else
    status=$?
  fi

  # needs_rebuild returns:
  #   0 => rebuild required
  #   1 => image is up to date
  #   2+ => check failed
  case "${status}" in
    0)
      if [[ -n "${NEEDS_REBUILD_OUTPUT:-}" ]]; then
        echo "Rebuild reason for ${AGENT} (${BASE_ALIAS}):"
        print_needs_rebuild_output
      fi
      echo "Needs build ${AGENT} (${BASE_ALIAS}) for ${AICAGE_VERSION}"
      append_build "${AGENT}" "${BASE_ALIAS}"
      ;;
    1)
      echo "Up-to-date ${AGENT} (${BASE_ALIAS})"
      ;;
    *)
      if [[ -n "${NEEDS_REBUILD_OUTPUT:-}" ]]; then
        print_needs_rebuild_output >&2
      fi
      echo "Failed to determine rebuild for ${AGENT} (${BASE_ALIAS})" >&2
      return 1
      ;;
  esac
}

# Parse the public CLI, then execute main using the populated named variables.
while [[ $# -gt 0 ]]; do
  case "$1" in
    --aicage-version)
      AICAGE_VERSION="${2:-}"
      shift 2
      ;;
    --agent)
      AGENT="${2:-}"
      shift 2
      ;;
    --base-alias)
      BASE_ALIAS="${2:-}"
      shift 2
      ;;
    --agent-version)
      AGENT_VERSION="${2:-}"
      shift 2
      ;;
    --build-list)
      BUILD_LIST="${2:-}"
      shift 2
      ;;
    --build-list-lock)
      BUILD_LIST_LOCK="${2:-}"
      shift 2
      ;;
    --base-metadata-file)
      BASE_METADATA_FILE="${2:-}"
      shift 2
      ;;
    --force-build)
      FORCE_BUILD=1
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      _die "Unknown argument: $1"
      ;;
  esac
done

main
