name: Version Image Check

"on":
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  version-image-check:
    name: Version image check (${{ matrix.platform }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3  # v4.1.0
      - name: Run version image check
        env:
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/version-image-check.sh
