name: Version Image Check

"on":
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  version-image-check:
    name: Version image check (${{ matrix.platform }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a  # v4.0.0
      - name: Run version image check
        env:
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/version-image-check.sh
